export function loadCatalog() {
  const letters = Array.from({ length: 26 }, (_, index) => {
    const upper = String.fromCharCode(65 + index);
    return {
      slug: upper.toLowerCase(),
      label: upper,
    };
  });

  const numbers = Array.from({ length: 20 }, (_, index) => {
    const value = (index + 1).toString();
    return {
      slug: value,
      label: value,
    };
  });

  return [
    {
      key: "colors",
      label: "Colors",
      items: [
        { slug: "red", label: "Red" },
        { slug: "orange", label: "Orange" },
        { slug: "yellow", label: "Yellow" },
        { slug: "green", label: "Green" },
        { slug: "blue", label: "Blue" },
        { slug: "purple", label: "Purple" },
        { slug: "pink", label: "Pink" },
        { slug: "brown", label: "Brown" },
        { slug: "black", label: "Black" },
        { slug: "white", label: "White" },
        { slug: "gray", label: "Gray" },
        { slug: "silver", label: "Silver" },
        { slug: "gold", label: "Gold" },
        { slug: "turquoise", label: "Turquoise" },
        { slug: "lime", label: "Lime" },
        { slug: "magenta", label: "Magenta" },
        { slug: "cyan", label: "Cyan" },
        { slug: "indigo", label: "Indigo" },
        { slug: "violet", label: "Violet" },
        { slug: "maroon", label: "Maroon" },
        { slug: "navy", label: "Navy" },
        { slug: "olive", label: "Olive" },
        { slug: "teal", label: "Teal" },
        { slug: "coral", label: "Coral" },
        { slug: "beige", label: "Beige" }
      ],
    },
    {
      key: "letters",
      label: "Letters",
      items: letters,
    },
    {
      key: "numbers",
      label: "Numbers",
      items: numbers,
    },
    {
      key: "animals",
      label: "Animals",
      items: [
        { slug: "ant", label: "Ant" },
        { slug: "bear", label: "Bear" },
        { slug: "bee", label: "Bee" },
        { slug: "bird", label: "Bird" },
        { slug: "butterfly", label: "Butterfly" },
        { slug: "cat", label: "Cat" },
        { slug: "chicken", label: "Chicken" },
        { slug: "cow", label: "Cow" },
        { slug: "crab", label: "Crab" },
        { slug: "deer", label: "Deer" },
        { slug: "dog", label: "Dog" },
        { slug: "dolphin", label: "Dolphin" },
        { slug: "duck", label: "Duck" },
        { slug: "eagle", label: "Eagle" },
        { slug: "elephant", label: "Elephant" },
        { slug: "fish", label: "Fish" },
        { slug: "fox", label: "Fox" },
        { slug: "giraffe", label: "Giraffe" },
        { slug: "goat", label: "Goat" },
        { slug: "hamster", label: "Hamster" },
        { slug: "horse", label: "Horse" },
        { slug: "ladybug", label: "Ladybug" },
        { slug: "lion", label: "Lion" },
        { slug: "lobster", label: "Lobster" },
        { slug: "monkey", label: "Monkey" },
        { slug: "mouse", label: "Mouse" },
        { slug: "octopus", label: "Octopus" },
        { slug: "owl", label: "Owl" },
        { slug: "penguin", label: "Penguin" },
        { slug: "pig", label: "Pig" },
        { slug: "rabbit", label: "Rabbit" },
        { slug: "rooster", label: "Rooster" },
        { slug: "shark", label: "Shark" },
        { slug: "sheep", label: "Sheep" },
        { slug: "spider", label: "Spider" },
        { slug: "squirrel", label: "Squirrel" },
        { slug: "tiger", label: "Tiger" },
        { slug: "whale", label: "Whale" },
        { slug: "wolf", label: "Wolf" },
        { slug: "zebra", label: "Zebra" },
      ],
    },
    {
      key: "machines",
      label: "Machines",
      items: [
        { slug: "ambulance", label: "Ambulance" },
        { slug: "bicycle", label: "Bicycle" },
        { slug: "boat", label: "Boat" },
        { slug: "bulldozer", label: "Bulldozer" },
        { slug: "bus", label: "Bus" },
        { slug: "car", label: "Car" },
        { slug: "crane", label: "Crane" },
        { slug: "excavator", label: "Excavator" },
        { slug: "fire-truck", label: "Fire Truck" },
        { slug: "forklift", label: "Forklift" },
        { slug: "helicopter", label: "Helicopter" },
        { slug: "jet-ski", label: "Jet Ski" },
        { slug: "monster-truck", label: "Monster Truck" },
        { slug: "motorcycle", label: "Motorcycle" },
        { slug: "plane", label: "Plane" },
        { slug: "police-car", label: "Police Car" },
        { slug: "race-car", label: "Race Car" },
        { slug: "sailboat", label: "Sailboat" },
        { slug: "scooter", label: "Scooter" },
        { slug: "semi-truck", label: "Semi Truck" },
        { slug: "ship", label: "Ship" },
        { slug: "snowmobile", label: "Snowmobile" },
        { slug: "submarine", label: "Submarine" },
        { slug: "tank", label: "Tank" },
        { slug: "taxi", label: "Taxi" },
        { slug: "tractor", label: "Tractor" },
        { slug: "train", label: "Train" },
        { slug: "truck", label: "Truck" },
        { slug: "van", label: "Van" },
        { slug: "yacht", label: "Yacht" },
      ],
    },
    {
      key: "fruitveg",
      label: "Fruits & Veggies",
      items: [
        { slug: "apple", label: "Apple" },
        { slug: "avocado", label: "Avocado" },
        { slug: "banana", label: "Banana" },
        { slug: "beet", label: "Beet" },
        { slug: "broccoli", label: "Broccoli" },
        { slug: "cabbage", label: "Cabbage" },
        { slug: "carrot", label: "Carrot" },
        { slug: "cherry", label: "Cherry" },
        { slug: "corn", label: "Corn" },
        { slug: "cucumber", label: "Cucumber" },
        { slug: "grape", label: "Grape" },
        { slug: "kiwi", label: "Kiwi" },
        { slug: "lemon", label: "Lemon" },
        { slug: "lettuce", label: "Lettuce" },
        { slug: "lime", label: "Lime" },
        { slug: "mango", label: "Mango" },
        { slug: "onion", label: "Onion" },
        { slug: "orange", label: "Orange" },
        { slug: "peach", label: "Peach" },
        { slug: "pear", label: "Pear" },
        { slug: "pepper", label: "Pepper" },
        { slug: "pineapple", label: "Pineapple" },
        { slug: "potato", label: "Potato" },
        { slug: "radish", label: "Radish" },
        { slug: "spinach", label: "Spinach" },
        { slug: "squash", label: "Squash" },
        { slug: "strawberry", label: "Strawberry" },
        { slug: "tomato", label: "Tomato" },
        { slug: "watermelon", label: "Watermelon" },
        { slug: "zucchini", label: "Zucchini" },
      ],
    },
    {
      key: "food",
      label: "Food",
      items: [
        { slug: "bagel", label: "Bagel" },
        { slug: "bread", label: "Bread" },
        { slug: "burger", label: "Burger" },
        { slug: "butter", label: "Butter" },
        { slug: "cake", label: "Cake" },
        { slug: "candy", label: "Candy" },
        { slug: "cereal", label: "Cereal" },
        { slug: "cheese", label: "Cheese" },
        { slug: "chocolate", label: "Chocolate" },
        { slug: "cookie", label: "Cookie" },
        { slug: "cracker", label: "Cracker" },
        { slug: "donut", label: "Donut" },
        { slug: "egg", label: "Egg" },
        { slug: "honey", label: "Honey" },
        { slug: "ice-cream", label: "Ice Cream" },
        { slug: "jam", label: "Jam" },
        { slug: "milk", label: "Milk" },
        { slug: "muffin", label: "Muffin" },
        { slug: "noodles", label: "Noodles" },
        { slug: "pancake", label: "Pancake" },
        { slug: "pasta", label: "Pasta" },
        { slug: "pizza", label: "Pizza" },
        { slug: "popcorn", label: "Popcorn" },
        { slug: "pretzel", label: "Pretzel" },
        { slug: "rice", label: "Rice" },
        { slug: "salad", label: "Salad" },
        { slug: "sandwich", label: "Sandwich" },
        { slug: "soup", label: "Soup" },
        { slug: "waffle", label: "Waffle" },
        { slug: "yogurt", label: "Yogurt" },
      ],
    },
    {
      key: "jobs",
      label: "Jobs",
      items: [
        { slug: "teacher", label: "Teacher" },
        { slug: "doctor", label: "Doctor" },
        { slug: "nurse", label: "Nurse" },
        { slug: "firefighter", label: "Firefighter" },
        { slug: "police-officer", label: "Police Officer" },
        { slug: "chef", label: "Chef" },
        { slug: "farmer", label: "Farmer" },
        { slug: "artist", label: "Artist" },
        { slug: "driver", label: "Driver" },
        { slug: "engineer", label: "Engineer" },
        { slug: "scientist", label: "Scientist" },
        { slug: "lawyer", label: "Lawyer" },
        { slug: "judge", label: "Judge" },
        { slug: "dentist", label: "Dentist" },
        { slug: "veterinarian", label: "Veterinarian" },
        { slug: "mechanic", label: "Mechanic" },
        { slug: "electrician", label: "Electrician" },
        { slug: "plumber", label: "Plumber" },
        { slug: "carpenter", label: "Carpenter" },
        { slug: "architect", label: "Architect" },
        { slug: "designer", label: "Designer" },
        { slug: "photographer", label: "Photographer" },
        { slug: "musician", label: "Musician" },
        { slug: "singer", label: "Singer" },
        { slug: "dancer", label: "Dancer" },
        { slug: "actor", label: "Actor" },
        { slug: "writer", label: "Writer" },
        { slug: "journalist", label: "Journalist" },
        { slug: "reporter", label: "Reporter" },
        { slug: "librarian", label: "Librarian" },
        { slug: "lifeguard", label: "Lifeguard" },
        { slug: "mailman", label: "Mail Carrier" },
        { slug: "delivery-person", label: "Delivery Person" },
        { slug: "cashier", label: "Cashier" },
        { slug: "waiter", label: "Waiter" },
        { slug: "barber", label: "Barber" },
        { slug: "hairdresser", label: "Hairdresser" },
        { slug: "cleaner", label: "Cleaner" },
        { slug: "security-guard", label: "Security Guard" }
      ],
    },
  ];
}
